import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const rootDir = join(import.meta.dir, "..");

test("meeting-api CI installs a complete hash-locked wheel set", () => {
  const sourcePath = "apps/meeting-api/backend/requirements.txt";
  const lockPath =
    "apps/meeting-api/backend/requirements-ci-cp313-linux-x86_64.txt";
  const workflow = Bun.YAML.parse(
    readFileSync(join(rootDir, ".github", "workflows", "meeting-api-ci.yml"), "utf8"),
  );
  const install = workflow.jobs.backend.steps.find(
    (step) => step.name === "Install backend dependencies",
  );

  expect(install).toBeDefined();
  const installCommand = install.run.replace(/\s+/g, " ").trim();
  expect(installCommand).toBe(
    `python -m pip install --only-binary=:all: --require-hashes -r ${lockPath}`,
  );
  expect(install.run).toMatch(/^python -m pip install\b/);
  expect(install.run).toContain("--only-binary=:all:");
  expect(install.run).toContain("--require-hashes");
  expect(install.run).toContain(`-r ${lockPath}`);
  expect(install.run).not.toContain("--upgrade pip");
  expect(install.run).not.toContain("&&");

  const sourcePins = readFileSync(join(rootDir, sourcePath), "utf8")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
  expect(sourcePins.length).toBeGreaterThan(0);
  const sourceDigest = createHash("sha256")
    .update(`${sourcePins.join("\n")}\n`, "utf8")
    .digest("hex");
  const lock = readFileSync(join(rootDir, lockPath), "utf8").replace(/\r\n?/g, "\n");
  expect(lock).toContain(`# source-pins-sha256: ${sourceDigest}`);
  expect(lock).toContain("# This file was autogenerated by uv");
  expect(lock).toContain("#    node scripts/lock-meeting-api-ci.mjs");

  const lockScript = readFileSync(
    join(rootDir, "scripts", "lock-meeting-api-ci.mjs"),
    "utf8",
  );
  for (const argument of [
    "--generate-hashes",
    "--no-strip-extras",
    "--python-version",
    '"3.13"',
    "--python-platform",
    '"x86_64-unknown-linux-gnu"',
    "--no-build",
    '"https://pypi.org/simple"',
  ]) {
    expect(lockScript).toContain(argument);
  }

  const normalizeName = (name) => name.toLowerCase().replace(/[-_.]+/g, "-");
  const parseName = (nameWithExtras) => {
    const [, name, extras = ""] = nameWithExtras.match(
      /^([A-Za-z0-9_.-]+)(?:\[([A-Za-z0-9_.,-]+)\])?$/,
    );
    return {
      name: normalizeName(name),
      extras: new Set(extras ? extras.split(",").map(normalizeName) : []),
    };
  };
  const sourceByName = new Map();
  for (const sourcePin of sourcePins) {
    const match = sourcePin.match(
      /^([A-Za-z0-9_.-]+(?:\[[A-Za-z0-9_.,-]+\])?)==([^\s*]+)$/,
    );
    expect(match).not.toBeNull();
    const [, nameWithExtras, version] = match;
    const parsed = parseName(nameWithExtras);
    expect(sourceByName.has(parsed.name)).toBe(false);
    sourceByName.set(parsed.name, { ...parsed, version });
  }

  const entryPattern =
    /^([A-Za-z0-9_.-]+(?:\[[A-Za-z0-9_.,-]+\])?)==([A-Za-z0-9][A-Za-z0-9.!+_-]*) \\$/gm;
  for (const line of lock.split("\n")) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    if (!line.startsWith(" ")) {
      expect(line).toMatch(
        /^[A-Za-z0-9_.-]+(?:\[[A-Za-z0-9_.,-]+\])?==[A-Za-z0-9][A-Za-z0-9.!+_-]* \\$/,
      );
      continue;
    }
    expect(line.trimEnd().replace(/ \\$/, "")).toMatch(
      /^\s*--hash=sha256:[a-f0-9]{64}$/,
    );
  }
  const starts = [...lock.matchAll(entryPattern)];
  expect(starts.length).toBeGreaterThanOrEqual(sourcePins.length);
  const lockNames = starts.map((match) =>
    normalizeName(match[1].replace(/\[.*\]$/, "")),
  );
  expect(lockNames).toEqual(lockNames.toSorted());
  const lockedByName = new Map();
  for (const [index, match] of starts.entries()) {
    const [, nameWithExtras, version] = match;
    const block = lock.slice(match.index, starts[index + 1]?.index ?? lock.length);
    const hashLines = block
      .split("\n")
      .filter((line) => line.trimStart().startsWith("--hash="));
    expect(hashLines.length).toBeGreaterThan(0);

    const parsed = parseName(nameWithExtras);
    expect(lockedByName.has(parsed.name)).toBe(false);
    const comments = block.split("\n").map((line) => line.trim());
    const direct = comments.some(
      (line) =>
        line === `# via -r ${sourcePath}` || line === `#   -r ${sourcePath}`,
    );
    lockedByName.set(parsed.name, { ...parsed, version, direct });
  }

  for (const [name, source] of sourceByName) {
    const locked = lockedByName.get(name);
    expect(locked?.version).toBe(source.version);
    expect(locked?.direct).toBe(true);
    for (const extra of source.extras) {
      expect(locked?.extras.has(extra)).toBe(true);
    }
  }
  for (const [name, locked] of lockedByName) {
    if (!locked.direct) continue;
    expect(sourceByName.get(name)?.version).toBe(locked.version);
  }
});
