/**
 * Explicit, count-locked inventory for the real DB Contract tier.
 *
 * This is intentionally a manifest, not a file-name/prefix convention. A test
 * that is added to one of the files below must be added here before it can be
 * reported as contract evidence. Ambiguous work is therefore fail-closed.
 */

export const TOPOLOGY_VERSION = 'db-contract-v1' as const

export const EXECUTION_CLASSES = {
  TRANSACTIONAL: 'transactional-suite',
  DEDICATED: 'dedicated-branch',
  CONTROL_PLANE: 'control-plane-unit',
} as const

export type ExecutionClass = (typeof EXECUTION_CLASSES)[keyof typeof EXECUTION_CLASSES]

export const SUITE_IDS = {
  ACCEPT_PATH: 'accept-path',
  BASELINE: 'baseline',
  COLLABORATION: 'collaboration',
  MEETING_INGEST: 'meeting-ingest',
  MEMORY_CURATOR: 'memory-curator',
  MEMORY_TIER: 'memory-tier',
  NEON_AUTHORITY: 'neon-authority',
  ROLE_PRIVILEGES: 'role-privileges',
  REAP: 'reap',
} as const

export type SuiteId = (typeof SUITE_IDS)[keyof typeof SUITE_IDS]

export interface TopologyEntry {
  readonly id: string
  readonly suiteId: SuiteId
  readonly executionClass: ExecutionClass
  /** A control-plane/unit assertion is never branch coverage. */
  readonly branchCoverage: boolean
  /** Exact Vitest title when the test is not generated by a table. */
  readonly title?: string
}

const transactional = (suiteId: SuiteId, id: string, title: string): TopologyEntry => ({
  id,
  suiteId,
  executionClass: EXECUTION_CLASSES.TRANSACTIONAL,
  branchCoverage: true,
  title,
})

const dedicated = (suiteId: SuiteId, id: string, title: string): TopologyEntry => ({
  id,
  suiteId,
  executionClass: EXECUTION_CLASSES.DEDICATED,
  branchCoverage: true,
  title,
})

const controlPlane = (suiteId: SuiteId, id: string, title: string): TopologyEntry => ({
  id,
  suiteId,
  executionClass: EXECUTION_CLASSES.CONTROL_PLANE,
  branchCoverage: false,
  title,
})

/** The exact 28 real-Neon assertions (19 transactional, 9 dedicated). */
const REAL_ASSERTIONS: readonly TopologyEntry[] = [
  transactional('accept-path', 'accept-path:2', '2: a malformed team_id at accept → invalid, proposal stays pending, no row (22P02 regression)'),
  transactional('accept-path', 'accept-path:3', '3: a successful accept stamps applied_from_proposal_id + applied_write and flips the proposal'),
  transactional('accept-path', 'accept-path:4', '4: a forced write failure (FK violation) → not applied, no partial row'),
  dedicated('accept-path', 'accept-path:5', '5: re-accepting an applied proposal is a no-op (not_pending), never a duplicate row'),
  dedicated('accept-path', 'accept-path:6', '6: crash after write, before flip → re-accept converges on the SAME row and flips (single row)'),
  dedicated('accept-path', 'accept-path:7', '7: a snapshotted team survives a 2nd team added before re-drive → uses persisted id (6055d30e)'),
  dedicated('accept-path', 'accept-path:8', '8: concurrent double-accept → exactly ONE row (the mandatory exactly-once proof)'),
  transactional('accept-path', 'accept-path:9', '9: a memory superseded out from under the proposal → stale, stays reviewable (no clobber)'),
  dedicated('accept-path', 'accept-path:flip-loser-create', 'flip-loser (create): a reject that wins the race COMPENSATES the orphaned row (996b674c)'),
  dedicated('accept-path', 'accept-path:flip-loser-non-create', 'flip-loser (non-create): an in-place update that loses to a reject logs LOUDLY, row left'),

  transactional('baseline', 'baseline:1', '1: create-with-defaults persists the resolved team + default status ids'),
  dedicated('baseline', 'baseline:10', '10: the full migration chain applies cleanly on a fresh branch (no schema drift)'),
  transactional('baseline', 'baseline:11', '11: accepting a proposal from another tenant → not_found (route maps to 404)'),
  transactional('baseline', 'baseline:12', '12: a non-create proposal with no target_id terminally fails (invalid)'),

  dedicated('collaboration', 'collaboration:1', 'enforces idempotency, ordering, cursor, ACL, references, links, archive, and immutability'),

  transactional('meeting-ingest', 'meeting-ingest:1', 'reads ONLY generated + promoted rows, and only for the mapped tenant'),
  transactional('meeting-ingest', 'meeting-ingest:2', 'mints exactly one run and stamps each proposal with reviewable provenance'),
  transactional('meeting-ingest', 'meeting-ingest:3', 'accepting a meeting proposal persists work_items.source = meeting'),
  dedicated('meeting-ingest', 'meeting-ingest:4', 'proposes each candidate exactly once — including across rematerialization'),
  transactional('meeting-ingest', 'meeting-ingest:5', 'a run with no candidates still mints the run and proposes nothing'),

  transactional('memory-curator', 'memory-curator:1', 'never names another user’s private memory as a collision — and DOES name the org one'),
  transactional('memory-curator', 'memory-curator:2', 'never names a memory from ANOTHER tenant, however well it matches'),
  transactional('memory-curator', 'memory-curator:3', 'reports a real contradiction against a real row (the verdict earns its keep)'),

  transactional('memory-tier', 'memory-tier:1', 'the CHECK rejects both malformed tiers and accepts both valid ones'),
  transactional('memory-tier', 'memory-tier:2', "visibility DEFAULTS to 'org' when the insert omits it (the zero-touch migration guarantee)"),
  transactional('memory-tier', 'memory-tier:3', 'the dual-lane retrieval index exists with the expected column order'),
  transactional('memory-tier', 'memory-tier:4', 'INVARIANT (a), for real: a non-owner retrieves ZERO private rows on every path'),
  transactional('memory-tier', 'memory-tier:5', 'attribution rows persist the tier for both lanes'),
]

/** The exact 29 control-plane/unit assertions; none provide branch coverage. */
const CONTROL_PLANE_ASSERTIONS: readonly TopologyEntry[] = [
  controlPlane('neon-authority', 'neon-authority:1', 'provisions canonical runtime roles before applying per-test migrations'),
  controlPlane('neon-authority', 'neon-authority:2', 'fails closed before migrations when runtime role provisioning fails'),
  controlPlane('neon-authority', 'neon-authority:3', 'advances both recognized histories through canonical 0021'),
  controlPlane('neon-authority', 'neon-authority:4', 'accepts only an empty test-only root with the repaired variant'),
  controlPlane('neon-authority', 'neon-authority:5', 'rejects production project id without exposing identifiers'),
  controlPlane('neon-authority', 'neon-authority:6', 'rejects production child claimed empty without exposing identifiers'),
  controlPlane('neon-authority', 'neon-authority:7', 'rejects non-root branch without exposing identifiers'),
  controlPlane('neon-authority', 'neon-authority:8', 'rejects nonempty catalog without exposing identifiers'),
  controlPlane('neon-authority', 'neon-authority:9', 'rejects wrong history variant without exposing identifiers'),
  controlPlane('neon-authority', 'neon-authority:10', 'requires a separate non-root branch derived from production history'),
  controlPlane('neon-authority', 'neon-authority:11', 'requires create, bootstrap, verify, delete, and deletion proof in cleanup evidence'),
  controlPlane('neon-authority', 'neon-authority:12', 'reports the real lane as INCOMPLETE without control-plane credentials'),
  controlPlane('neon-authority', 'neon-authority:13', 'fails the required real lane instead of silently skipping when requested'),
  controlPlane('neon-authority', 'neon-authority:14', 'does not claim real conformance without credentials'),
  controlPlane('neon-authority', 'neon-authority:15', 'runs the required sequence through a mocked control plane and cleans up both resources'),
  controlPlane('neon-authority', 'neon-authority:16', 'cleans the disposable project when derived-branch creation fails'),
  controlPlane('neon-authority', 'neon-authority:17', 'bounds every request and retries only safe GET or DELETE operations'),
  controlPlane('neon-authority', 'neon-authority:18', 'polls project deletion until the control plane proves 404'),

  controlPlane('role-privileges', 'role-privileges:1', 'accepts separate NOLOGIN grant roles with non-admin login memberships'),
  controlPlane('role-privileges', 'role-privileges:2', 'rejects LOGIN grant role'),
  controlPlane('role-privileges', 'role-privileges:3', 'rejects role escalation'),
  controlPlane('role-privileges', 'role-privileges:4', 'rejects admin option membership'),
  controlPlane('role-privileges', 'role-privileges:5', 'rejects cross-service membership'),
  controlPlane('role-privileges', 'role-privileges:6', 'rejects missing and unauthorized login memberships'),
  controlPlane('role-privileges', 'role-privileges:7', 'describes allowed and denied probes without embedding credentials or SQL payloads'),

  controlPlane('reap', 'reap:1', 'matches only the exact `db-contract-<epoch>-<8hex>` shape createEphemeralBranch mints'),
  controlPlane('reap', 'reap:2', 'reaps only aged-out ephemeral branches (across pages) and spares every durable branch'),
  controlPlane('reap', 'reap:3', 'never deletes the configured parent branch even when it is old and matches the ephemeral name'),
  controlPlane('reap', 'reap:4', 'does not delete a stale same-prefix branch that lacks the expires_at marker'),
]

/** Explicit manifest; order is stable for evidence and review. */
export const SUITE_MANIFEST: readonly TopologyEntry[] = [...REAL_ASSERTIONS, ...CONTROL_PLANE_ASSERTIONS]

export const EXPECTED_TRANSACTIONAL_ASSERTIONS = 19 as const
export const EXPECTED_DEDICATED_ASSERTIONS = 9 as const
export const EXPECTED_REAL_ASSERTIONS = 28 as const
export const EXPECTED_CONTROL_PLANE_ASSERTIONS = 29 as const
export const EXPECTED_TOTAL_ASSERTIONS = 57 as const

/** Independent count lock; summaries below are derived from the manifest. */
export const CONTROL_PLANE_ASSERTION_COUNTS = {
  'neon-authority': 18,
  'role-privileges': 7,
  reap: 4,
} as const

const MANIFEST_BY_ID = new Map(SUITE_MANIFEST.map((entry) => [entry.id, entry]))

/** Classify an already-normalized manifest id. Unknown ids are hard failures. */
export function classifyTestId(id: string): TopologyEntry | undefined {
  return MANIFEST_BY_ID.get(id)
}

/** Resolve a Vitest file + exact title through the explicit manifest. */
export function resolveTestId(fileName: string, title: string): TopologyEntry | undefined {
  const suiteId = fileName
    .replaceAll('\\', '/')
    .split('/')
    .pop()
    ?.replace(/\.test\.tsx?$/, '')
  if (!suiteId || !Object.values(SUITE_IDS).includes(suiteId as SuiteId)) return undefined
  return SUITE_MANIFEST.find((entry) => entry.suiteId === suiteId && entry.title === title)
}

export interface TopologySummary {
  readonly totalAssertions: number
  readonly realAssertions: number
  readonly controlPlaneAssertions: number
  readonly transactionalAssertions: number
  readonly dedicatedAssertions: number
  readonly controlPlaneBySuite: {
    readonly 'neon-authority': number
    readonly 'role-privileges': number
    readonly reap: number
  }
}

export function getTopologySummary(manifest: readonly TopologyEntry[] = SUITE_MANIFEST): TopologySummary {
  const transactionalAssertions = manifest.filter(
    (entry) => entry.executionClass === EXECUTION_CLASSES.TRANSACTIONAL,
  ).length
  const dedicatedAssertions = manifest.filter(
    (entry) => entry.executionClass === EXECUTION_CLASSES.DEDICATED,
  ).length
  const controlPlaneAssertions = manifest.filter(
    (entry) => entry.executionClass === EXECUTION_CLASSES.CONTROL_PLANE,
  ).length
  const controlPlaneBySuite = {
    'neon-authority': manifest.filter(
      (entry) => entry.executionClass === EXECUTION_CLASSES.CONTROL_PLANE && entry.suiteId === SUITE_IDS.NEON_AUTHORITY,
    ).length,
    'role-privileges': manifest.filter(
      (entry) => entry.executionClass === EXECUTION_CLASSES.CONTROL_PLANE && entry.suiteId === SUITE_IDS.ROLE_PRIVILEGES,
    ).length,
    reap: manifest.filter(
      (entry) => entry.executionClass === EXECUTION_CLASSES.CONTROL_PLANE && entry.suiteId === SUITE_IDS.REAP,
    ).length,
  } as const

  return {
    totalAssertions: manifest.length,
    realAssertions: transactionalAssertions + dedicatedAssertions,
    controlPlaneAssertions,
    transactionalAssertions,
    dedicatedAssertions,
    controlPlaneBySuite,
  }
}
